### ISSUE TITLE
代码使用相关问题

### ISSUE THREAD

**Issue by Hondlus** [Broad-sky/SOLOv2-TensorRT#4]
我按照您的步骤，执行第二个命令报错，提示找不到命令convertModel，请问是怎么回事

**Comment by Broad-sky** [comment]
> 我按照您的步骤，执行第二个命令报错，提示找不到命令convertModel，请问是怎么回事

你可以截个图，发出来看看

**Comment by Broad-sky** [comment]
> > > 我按照您的步骤，执行第二个命令报错，提示找不到命令convertModel，请问是怎么回事
> > 
> > 
> > 你可以截个图，发出来看看
> 
> ![image](https://user-images.githubusercontent.com/48700890/174698262-1be001e8-49d1-4613-ad9a-92ca835bcaac.jpeg)

赋个权限试一下
